version: '3.1'

services:
    db:
        image: "handuy1992/postgres"
        volumes:
            - data:/var/lib/postgresql/data
        networks:
            - myapp
        secrets:
            - postgre_password
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgre_password
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
    golang:
        image: "handuy1992/golang-crud"
        ports:
            - 8005:8080
        networks:
            - myapp
        deploy:
            mode: replicated
            replicas: 3
        depends_on:
            - db


networks:
    myapp:

secrets:
    postgre_password:
        file: ./postgre_password.txt

volumes:
    data:

